cgx/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = 'cgx'

urlpatterns = [
    path('view-bioconfirm', views.BioConfirmView.as_view(), name='bioconfirm'),
    path('add-bioconfirm', views.AddBioConfirmView.as_view(), name='add-bioconfirm'),
    path('cgx_upload_data/', views.upload_bcm, name='upload_bcm'),
    path('<uuid:bioconfirm_id>/bioconfirm-report.pdf', views.PdfBioconfirm.as_view(), name='bioconfirm_print'),
]

insurance/models.py
import uuid
import datetime
from django.db import models

from django.utils import timezone

from cgx.models import Agent, Manager

# type of test choices
CARRIER = 1
CGX = 2
CGX_CARRIER = 3

TYPE_OF_TEST_CHOICES = (
    (CARRIER, 'Carrier'),
    (CGX, 'CGX'),
    (CGX_CARRIER, 'CGX/Carrier')
)


class TypeOfInsurance(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    name = models.CharField(max_length=250, verbose_name='Name of the Insurance')
    notes = models.TextField(null=True, blank=True)

    def __str__(self):
        return self.name


class Insurance(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    name = models.CharField(max_length=250, verbose_name='Patient Name', null=True, blank=True, unique=True)
    promo_code = models.CharField(max_length=250, verbose_name='Promo Code', null=True, blank=True)
    agent = models.ForeignKey(Agent, verbose_name='Agent name', on_delete=models.PROTECT, null=True, blank=True)
    manager = models.ForeignKey(Manager, verbose_name='Manager Name', on_delete=models.PROTECT, null=True, blank=True)
    date_of_birth = models.DateField(default=datetime.date.today, verbose_name='Date of Birth', null= True, blank=True)
    state = models.CharField(max_length=250, verbose_name='State', null=True, blank=True)
    type_of_insurance = models.ForeignKey(TypeOfInsurance, verbose_name='Type of Insurance', on_delete=models.PROTECT, null=True, blank=True)
    test = models.CharField(max_length=250, verbose_name='Test',  null=True, blank=True)
    active_inactive = models.CharField(max_length=250, verbose_name='Active/Inactive', null=True, blank=True)
    status = models.CharField(max_length=150, verbose_name='Status', null=True, blank=True)
    insurance_status = models.CharField(max_length=200, verbose_name='Insurance Status', null=True, blank=True)
    policy_number = models.CharField(max_length=250, verbose_name='Policy Number', null=True, blank=True)
    verification_date = models.DateField(default=datetime.date.today, null=True, blank=True)
    deductible_remainding = models.CharField(max_length=250, verbose_name='Deductible Remainding', null=True, blank=True)
    notes = models.TextField(null=True, blank=True)
    patient_id_photo = models.ImageField(upload_to='insurance/patient-id-photo/', max_length=1000, null=True, blank=True)
    insurance_card_photo_front = models.ImageField(upload_to='insurance/insurance-card-photo-front/', max_length=1000, null=True, blank=True)
    insurance_card_photo_back = models.ImageField(upload_to='insurance/insurance-card-photo-back/', max_length=1000, null=True, blank=True)
    additional_insurance_cards = models.ImageField(upload_to='insurance/additional-insurance-cards/', max_length=1000, null=True, blank=True)
    consent_recording = models.FileField(upload_to='insurance/consent_recording/', max_length=1000, null=True, blank=True)
    date_created = models.DateField(default=datetime.date.today, null=True, blank=True)
    created_by = models.CharField(max_length=100, null=True, blank=True)
    updated_by = models.CharField(max_length=100, null=True, blank=True)
    user_promo_code = models.CharField(max_length=100, verbose_name="Promo code of the agent who created this record.", null=True, blank=True)

    class Meta:
        verbose_name_plural = 'Insurance records'
        ordering = ['name']

    def __str__(self):
        return self.name

insurance/views.py
import django_filters
from django_filters import DateFilter, CharFilter

from rest_framework import viewsets, filters
from rest_framework.authentication import SessionAuthentication, BasicAuthentication
from rest_framework.permissions import IsAuthenticated
from drf_renderer_xlsx.mixins import XLSXFileMixin
from drf_renderer_xlsx.renderers import XLSXRenderer

from django.shortcuts import render
from django.views.generic import TemplateView

from cgx.models import Agent, Manager
from .models import Insurance, TypeOfInsurance

from cgx.serializers import AgentSerializer, ManagerSerializer
from .serializers import InsuranceSerializer, TypeOfInsuranceSerializer


class CsrftExemptSessionAuthentication(SessionAuthentication):

    def enforce_csrf(self, request):
        return  # will not enforce a csrf check


class AgentViewSet(viewsets.ModelViewSet):
    queryset = Agent.objects.all()
    permission_classes = (IsAuthenticated,)
    serializer_class = AgentSerializer


class ManagerViewSet(viewsets.ModelViewSet):
    queryset = Manager.objects.all()
    permission_classes = (IsAuthenticated,)
    serializer_class = ManagerSerializer


class TypeOfInsuranceViewSet(viewsets.ModelViewSet):
    queryset = TypeOfInsurance.objects.all()
    permission_classes = (IsAuthenticated,)
    serializer_class = TypeOfInsuranceSerializer


class InsuranceFilter(django_filters.FilterSet):
    date_created__gte = DateFilter(field_name='date_created', lookup_expr='gte')
    date_created__lte = DateFilter(field_name='date_created', lookup_expr='lte')
    name = CharFilter(field_name='name', lookup_expr='icontains')
    promo_code = CharFilter(field_name='promo_code', lookup_expr='icontains')

    class Meta:
        model = Insurance
        fields = ('date_created__gte', 'date_created__lte',
                  'name', 'promo_code',)


class InsuranceViewSet(XLSXFileMixin, viewsets.ModelViewSet):
    # queryset = Insurance.objects.all()
    serializer_class = InsuranceSerializer
    authentication_classes = (CsrftExemptSessionAuthentication, BasicAuthentication)
    permission_classes = (IsAuthenticated,)
    filter_class = (InsuranceFilter)
    search_fields = ('name', 'promo_code')
    filename = 'insurance-reports.xlsx'

    def get_queryset(self):
        user = self.request.user
        position = self.request.user.position
        if position == 'Manager':
            queryset = Insurance.objects.filter(manager__name=user)
        else:
            queryset = Insurance.objects.filter(agent__name=user)
        return queryset

templates/insurance/add_info_insurance.html
<div id="insurance-app" v-cloak>
  <form v-on:submit.prevent="addInsurance" enctype="multipart/form-data">
    {% csrf_token %}
    <h5 class="title1">
      Patient Informations
    </h5>
    <!-- form row -->
    <div class="form-row">
      <div class="form-group col-md-4 col-sm-12">
        <label for="inputEmail4">Patient Name</label>
        <input type="text" class="form-control form-control-sm" id="inputPatientName" v-model="newInsurance.name" :disabled="loading == true">
      </div>
      <div class="form-group col-md-2 col-sm-12">
        <label for="inputEmail4">Promo Code</label>
        <input type="text" class="form-control form-control-sm" id="inputPromo" v-model="newInsurance.promo_code" :disabled="loading == true">
      </div>
      <div class="form-group col-md-2 col-sm-12">
        <label>Agent Name</label>
        <select id="inputAgent" class="form-control form-control-sm" v-model="newInsurance.agent" :disabled="loading == true" required>
          <option v-for="agent in agentNames">[[agent.name]]</option>
        </select>
      </div>
      <div class="form-group col-md-2 col-sm-12">
        <label>Manager Name</label>
        <select id="inputTest" class="form-control form-control-sm" v-model="newInsurance.manager" :disabled="loading == true">
          <option v-for="manager in managerNames">[[manager.name]]</option>
        </select>
      </div>
      <div class="form-group col-md-2 col-sm-12">
        <label>Type of Insurance</label>
        <select id="inputTest" class="form-control form-control-sm" v-model="newInsurance.type_of_insurance" :disabled="loading == true">
          <option v-for="insuranceType in typeOfInsurance">[[ insuranceType.name ]]</option>
        </select>
      </div>
    </div>
    <div class="form-row">
      <div class="form-group col-md-3 col-sm-12 ">
        <label for="input">State</label>
        <input type="text" class="form-control form-control-sm" id="inputState" v-model="newInsurance.state" placeholder="State">
      </div>
      <div class="form-group col-md-2 col-sm-12">
        <label for="inputState">Status</label>
        <input type="text" class="form-control form-control-sm" v-model="newInsurance.status" :disabled="loading == true">
      </div>
      <div class="form-group col-md-4 col-sm-12">
        <label for="inputState">Test</label>
        <input type="text" class="form-control form-control-sm" v-model="newInsurance.test" :disabled="loading == true">
      </div>
      <div class="form-group col-md-3 col-sm-12">
        <label for="inputState">Active/Inactive</label>
        <input type="text" class="form-control form-control-sm" v-model="newInsurance.active_inactive" :disabled="loading == true">
      </div>
      <div class="form-group col-md-2 col-sm-12">
        <label for="inputState">Insurance Status</label>
        <input type="text" class="form-control form-control-sm" v-model="newInsurance.insurance_status" :disabled="loading == true">
      </div>
      <div class="form-group col-md-2 col-sm-12">
        <label>Policy Number</label>
        <input type="text" class="form-control form-control-sm" v-model="newInsurance.policy_number" :disabled="loading == true">
      </div>
      <div class="form-group col-md-4 col-sm-12">
        <label>Deductible remainding</label>
        <input type="text" class="form-control form-control-sm" v-model="newInsurance.deductible_remainding" :disabled="loading == true">
      </div>
      <div class="form-group col-md-2 col-sm-12">
        <label for="inputEmail4">Date of birth</label>
        <input type="date" class="form-control form-control-sm" id="inputDate" v-model="newInsurance.date_of_birth" :disabled="loading == true">
      </div>
      <div class="form-group col-md-2 col-sm-12">
        <label for="inputEmail4">Verification Date</label>
        <input type="date" class="form-control form-control-sm" id="inputDate" v-model="newInsurance.verification_date" :disabled="loading == true">
      </div>
    </div>
    <div class="form-row">
      <div class="form-group col-md-12 col-sm-12">
        <label>Notes</label>
        <textarea class="form-control" name="name" rows="10" cols="80" v-model="newInsurance.notes"></textarea>
      </div>
    </div>
    <!-- end form-row -->
    <hr />
    <div>
      <h5 class="title1">
        Attachments
      </h5>
      <div>
        <div class="row">
          <div class="form-group col-sm-12">
            <label>Patient ID Photo</label>
            <div class="custom-file" v-on:click="$refs.patient_id_photo_ref.click()" >
              <input
                  type="file" accept="image/*" class="form-control form-control-file form-control-sm"
                  name="patient_id_photo" id="inputIDPhoto"
                  v-on:change="onFileChange($event)"
                  ref="patient_id_photo_ref"
                  :disabled="loading == true"
              >
              <label class="custom-file-label" for="customFile">
                <template v-if="!newInsurance.patient_id_photo.name">
                  Choose file
                </template>
                <template v-else>
                  [[ newInsurance.patient_id_photo.name ]]
                </template>
              </label>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-sm-12">
          </div>
        </div>
        <div class="row">
          <div class="form-group col-sm-12 col-md-6">
            <label>Insurance card photo</label>
            <div class="custom-file" v-on:click="$refs.insurance_card_photo_front_ref.click()" >
              <input
                  type="file" accept="image/*" class="form-control form-control-file form-control-sm"
                  name="insurance_card_photo_front" id="inputInsuranceFront"
                  v-on:change="onFileChange($event)"
                  ref="insurance_card_photo_front_ref"
                  :dsiabled="loading == true"
              >
              <label class="custom-file-label" for="customFile">
                <template v-if="!newInsurance.insurance_card_photo_front.name">
                  Choose file
                </template>
                <template v-else>
                  [[ newInsurance.insurance_card_photo_front.name ]]
                </template>
              </label>
            </div>
            <small class="text-muted">Insurance card photo front</small>
          </div>
          <div class="form-group col-sm-12 col-md-6">
            <label>&nbsp;</label>
            <div class="custom-file" v-on:click="$refs.insurance_card_photo_back_ref.click()" >
              <input
                  type="file" accept="image/*" class="form-control form-control-file form-control-sm"
                  name="insurance_card_photo_back" id="inputInsuranceFront"
                  v-on:change="onFileChange($event)"
                  ref="insurance_card_photo_back_ref"
                  :disabled="loading == true"
              >
              <label class="custom-file-label" for="customFile">
                <template v-if="!newInsurance.insurance_card_photo_back.name">
                  Choose file
                </template>
                <template v-else>
                  [[ newInsurance.insurance_card_photo_back.name ]]
                </template>
              </label>
            </div>
            <small class="text-muted">Insurance card photo back</small>
          </div>
        </div>
        <div class="row">
          <div class="form-group col-sm-12">
            <label>Additional Insurance card</label>
            <div class="custom-file" v-on:click="$refs.additional_insurance_cards_ref.click()">
              <input
                  type="file" accept="image/*" class="form-control form-control-file form-control-sm"
                  name="additional_insurance_cards" id="inputInsuranceAdditional"
                  v-on:change="onFileChange($event)"
                  ref="additional_insurance_cards_ref"
                  :disabled="loading == true"
              >
              <label class="custom-file-label" for="customFile">
                <template v-if="!newInsurance.additional_insurance_cards.name">
                  Choose file
                </template>
                <template v-else>
                  [[ newInsurance.additional_insurance_cards.name ]]
                </template>
              </label>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="form-group col-sm-12">
            <label>Consent Recording</label>
            <div class="custom-file" v-on:click="$refs.consent_recording_ref.click()">
              <input
                  type="file" accept="video/*" class="form-control form-control-file form-control-sm"
                  name="consent_recording" id="inputRecording"
                  v-on:change="onFileChange($event)"
                  ref="consent_recording_ref"
                  :disabled="loading == true"
              >
              <label class="custom-file-label" for="customFile" >
                <template v-if="!newInsurance.consent_recording.name">
                  Choose file
                </template>
                <template v-else>
                  [[ newInsurance.consent_recording.name ]]
                </template>
              </label>
            </div>
          </div>
        </div>
      </div>
    </div>
    <!-- end of attachments -->
    <template v-if="saving == true">
      <button class="btn btn-success save-btn-insurance" type="button" disabled style="float: right;">
        <span class="spinner-border spinner-border-sm" role="status" aria-hidden="true"></span>
        Saving...
      </button>
    </template>
    <template v-else-if="saving == false">
      <button type="submit" class="btn btn-success save-btn-insurance" style="float: right;">Save</button>
    </template>
  </form>
</div>
<!-- end of insurance app -->

templates/insurance/change_list_graph.html
{% extends "admin/change_list.html" %}
{% load staticfiles %}
{% block extrastyle %}
    {{ block.super }}
<link rel="stylesheet" href="{% static 'css/styles.css' %}">
{% endblock %}
{% block extrahead %}
    <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"/>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.0/Chart.min.js"></script>
    <script>
        var randomColorGenerator = function () {
            return '#' + (Math.random().toString(16) + '0000000').slice(2, 8);
        };
        var options = {
            responsive: true,
            maintainAspectRatio: true,
            legend: {
                position: 'left'
            },
            title: {
                display: true
            },
            animation: {
                animateScale: true,
                animateRotate: true
            }
        };
        window.onload = function () {
            var ctx = document.getElementById("insurance_status-chart");
            {% regroup cl.queryset|dictsort:"insurance_status" by insurance_status as insurance_status_list %}
            var lineChart = new Chart(ctx, {
                type: 'pie',
                data: {
                    labels: [{% for insurance_status in insurance_status_list %}'{{ insurance_status.grouper }}',{% endfor %}],
                    datasets: [{
                        data: [{% for insurance_status in insurance_status_list %}'{{ insurance_status.list|length }}',{% endfor %}],
                        backgroundColor: [{% for insurance_status in insurance_status_list %}randomColorGenerator(),{% endfor %}]
                    }]
                },
                options: options
            });
            ctx = document.getElementById("active_inactive-chart");
            {% regroup cl.queryset|dictsort:"active_inactive" by active_inactive as active_inactive_list %}
            lineChart = new Chart(ctx, {
                type: 'pie',
                data: {
                    labels: [{% for active_inactive in active_inactive_list %}'{{ active_inactive.grouper }}',{% endfor %}],
                    datasets: [{
                        data: [{% for active_inactive in active_inactive_list %}'{{ active_inactive.list|length }}',{% endfor %}],
                        backgroundColor: [{% for active_inactive in active_inactive_list %}randomColorGenerator(),{% endfor %}]
                    }]
                }, options: options
            });
            ctx = document.getElementById("type_of_insurance-chart");
            {% regroup cl.queryset|dictsort:"type_of_insurance" by type_of_insurance as type_of_insurance_list %}
            lineChart = new Chart(ctx, {
                type: 'pie',
                data: {
                    labels: [{% for type_of_insurance in type_of_insurance_list %}'{{ type_of_insurance.grouper }}',{% endfor %}],
                    datasets: [{
                        data: [{% for type_of_insurance in type_of_insurance_list %}'{{ type_of_insurance.list|length }}',{% endfor %}],
                        backgroundColor: [{% for type_of_insurance in type_of_insurance_list %}randomColorGenerator(),{% endfor %}]
                    }]
                }, options: options
            });
        }
    </script>
{% endblock %}
{% block content %}
    <hr>
    <div class="row">
        <div class="col-md-4">
          <label class="col-sm-offset-6">Insurance Status</label>
            <canvas id="insurance_status-chart" style="width: 100px !important;"></canvas>
        </div>
        <div class="col-sm-4">
          <label class="col-sm-offset-6">Active/Inactive</label>
            <canvas id="active_inactive-chart" style="width: 100px !important;"></canvas>
        </div>
        <div class="col-sm-4">
          <label class="col-sm-offset-6">Type of Insurance</label>
          <canvas id="type_of_insurance-chart" style="width 100px !important;"></canvas>
        </div>
    </div>
    {{ block.super }}
{% endblock %}

templates/insurance/hold_change_list_graph.html
{% extends "admin/change_list.html" %}
{% load staticfiles %}
{% block extrahead %}
    <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"/>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.0/Chart.min.js"></script>
    <script>
        var randomColorGenerator = function () {
            return '#' + (Math.random().toString(16) + '0000000').slice(2, 8);
        };
        var options = {
            responsive: true,
            maintainAspectRatio: true,
            legend: {
                position: 'left'
            },
            title: {
                display: true
            },
            animation: {
                animateScale: true,
                animateRotate: true
            }
        };
        window.onload = function () {
            var ctx = document.getElementById("state-chart");
            {% regroup cl.queryset|dictsort:"state" by get_state_display as state_list %}
            var lineChart = new Chart(ctx, {
                type: 'doughnut',
                data: {
                    labels: [{% for state in state_list %}'{{ state.grouper }}',{% endfor %}],
                    datasets: [{
                        data: [{% for state in state_list %}'{{ state.list|length }}',{% endfor %}],
                        backgroundColor: [{% for state in state_list %}randomColorGenerator(),{% endfor %}]
                    }]
                },
                options: options
            });
            ctx = document.getElementById("active_inactive-chart");
            {% regroup cl.queryset|dictsort:"active_inactive" by active_inactive as active_inactive_list %}
            lineChart = new Chart(ctx, {
                type: 'doughnut',
                data: {
                    labels: [{% for active_inactive in active_inactive_list %}'{{ active_inactive.grouper }}',{% endfor %}],
                    datasets: [{
                        data: [{% for active_inactive in active_inactive_list %}'{{ active_inactive.list|length }}',{% endfor %}],
                        backgroundColor: [{% for active_inactive in active_inactive_list %}randomColorGenerator(),{% endfor %}]
                    }]
                }, options: options
            });
        }
    </script>
{% endblock %}
{% block content %}
    <hr>
    <div class="row">
        <div class="col-md-4">
            <canvas id="state-chart" style="width: 100px !important;"></canvas>
        </div>
        <div class="col-sm-4">
            <canvas id="active_inactive-chart" style="width: 100px !important;"></canvas>
        </div>
    </div>
    {{ block.super }}
{% endblock %}