cgx/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = 'cgx'

urlpatterns = [
    path('view-bioconfirm', views.BioConfirmView.as_view(), name='bioconfirm'),
    path('add-bioconfirm', views.AddBioConfirmView.as_view(), name='add-bioconfirm'),
    path('cgx_upload_data/', views.upload_bcm, name='upload_bcm'),
    path('<uuid:bioconfirm_id>/bioconfirm-report.pdf', views.PdfBioconfirm.as_view(), name='bioconfirm_print'),
]

cgx/models.py
import uuid
import datetime
from django.db import models

from django.utils import timezone
from django.contrib import messages


# type of test choices
CARRIER = "CARRIER"
CGX = "CGX"
CGX_CARRIER = "CGX/CARRIER"
L = "L"

# STATUS_CHOICES
CGX_CGD = "CGX/CGD"
DUPLICATE = "DUPLICATE"
HOLD = "HOLD"
MISSING_INFORMATION = "MISSING INFORMATION"
REJECTED = "REJECTED"
WRONG_APPLICATION = "WRONG APPLICATION"
RFE = "Resubmit from Elite"
RESIGNED = "RESIGNED"
RA = "Requires Authorization"
REJ_HMO = "REJECTED HMO"
REJ_NO_ID = "REJECTED NO ID"
REJ_INELIGIBLE = "REJECTED INELIGIBLE"
REJ_INACTIVE = "REJECTED INACTIVE"
REJ_HIGD = "REJECTED - Higd ded 6880.37"
REJ_CARESOURCE = "REJECTED CARESOURCE"

# REASON_FOR_REJECTIONS_CHOICES
HD = 1
HIPAA = 2
RRA = 3

REASON_FOR_REJECTIONS_CHOICES = (
    (HD, "HIGH DEDUCTIBLE - 2400.00"),
    (HIPAA, "HIPAA VIOLATION"),
    (RRA, "REQUIRES AUTHENTICATION")
)


class Agent(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False, verbose_name="Agent id")
    name = models.CharField(max_length=50, verbose_name="Agent name", null=True, blank=True, unique=True)
    promo_code = models.CharField(max_length=50, null=True, blank=True)

    class Meta:
        verbose_name = 'Agent name'
        verbose_name_plural = 'Agent names'
        ordering = ['name']

    def __str__(self):
        return str(self.name)


class Manager(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False, verbose_name="Manager id")
    name = models.CharField(max_length=50, verbose_name="Manager name", null=True, blank=True, unique=True)

    class Meta:
        verbose_name = 'Manager name'
        verbose_name_plural = 'Manager names'
        ordering = ['name']

    def __str__(self):
        return str(self.name)


class Status(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False, verbose_name='Status id')
    name = models.CharField(max_length=250, verbose_name='Status', null=True, blank=True)

    class Meta:
        verbose_name = 'Status'
        verbose_name_plural = 'Statuses'
        ordering=['name']

    def __str__(self):
        return str(self.name)


class Test_choices(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False, verbose_name='Test choices id')
    name = models.CharField(max_length=250, verbose_name="Test choice", null=True, blank=True)

    class Meta:
        verbose_name = 'Test Choice'
        verbose_name_plural = 'Test Choices'
        ordering=['name']

    def __str__(self):
        return str(self.name)


class BioConfirmMaster(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    patient_name = models.CharField(max_length=250, verbose_name="Patient Name", null=True, blank=True, unique=True)
    patient_phone_number = models.CharField(max_length=250, verbose_name="Patient phone number", null=True, blank=True)
    promo_code = models.CharField(max_length=250, verbose_name="Promo Code", null=True, blank=True)
    agent = models.ForeignKey(Agent, verbose_name="Agent name", null=True, blank=True, on_delete=models.PROTECT)
    manager = models.ForeignKey(Manager, verbose_name="Manager name", null=True, blank=True, on_delete=models.PROTECT)
    date_app_rec = models.DateField(default=timezone.now, verbose_name="Date application recorded", null=True, blank=True)
    date_sample_rec = models.DateField(verbose_name="Date sample recorded", null=True, blank=True)
    type_of_test = models.ForeignKey(Test_choices, max_length=250, verbose_name="Test choices", null=True, blank=True, on_delete=models.PROTECT)
    date_of_qca = models.DateField(verbose_name="Date of QCA", null=True, blank=True)
    insurance_verified_tsg_verification = models.DateField(verbose_name="Insurance Verified/TSG Verification", null=True, blank=True)
    telemed_name = models.CharField(max_length=250, verbose_name="Telemed name", null=True, blank=True)
    date_submitted_to_telemed = models.DateField(verbose_name="Date submitted to telemed", null=True, blank=True)
    date_telemed_returned = models.DateField(verbose_name="Date telemed returned", null=True, blank=True)
    date_bioconfim_rec_app = models.DateField(verbose_name="Date bioconfirm recorded application", null=True, blank=True)
    date_paid = models.DateField(verbose_name="Date paid", null=True, blank=True)
    date_lab_recorded_app = models.DateField(null=True, blank=True)
    lab_type = models.CharField(max_length=250, null=True, blank=True)
    state = models.CharField(max_length=50, verbose_name="State", null=True, blank=True)
    status = models.ForeignKey(Status, max_length=250, verbose_name="Status", null=True, blank=True, on_delete=models.PROTECT)
    month = models.CharField(max_length=50, null=True, blank=True)
    insurance_company = models.CharField(max_length=50, verbose_name="Insurance company name", null=True, blank=True)
    notes = models.TextField(verbose_name="Notes", null=True, blank=True)
    rejection_date = models.DateField(verbose_name="Rejection Date", null=True, blank=True)
    patient_id_photo = models.ImageField(upload_to='bio-confirm-master/patient-id-photo/', max_length=1000, null=True, blank=True)
    insurance_card_photo_front = models.ImageField(upload_to='bio-confirm-master/insurance-card-photo-front/', max_length=1000, null=True, blank=True)
    insurance_card_photo_back = models.ImageField(upload_to='bio-confirm-master/insurance-card-photo-back/', max_length=1000, null=True, blank=True)
    additional_insurance_cards = models.ImageField(upload_to='bio-confirm-master/additional-insurance-cards/', max_length=1000, null=True, blank=True)
    consent_recording = models.FileField(upload_to='bio-confirm-master/consent-recording/', max_length=1000, null=True, blank=True)
    date_created = models.DateField(default=datetime.date.today, null=True, blank=True)
    created_by = models.CharField(max_length=100, null=True, blank=True)
    updated_by = models.CharField(max_length=100, null=True, blank=True)
    user_promo_code = models.CharField(max_length=100, verbose_name="Promo code of the agent who created this record.", null=True, blank=True)

    class Meta:
        ordering = ['patient_name']

    def __str__(self):
        return str(self.patient_name)

cgx/forms.py
from django import forms


class UploadFileForm(forms.Form):
    file = forms.FileField()

carrier/views.py
import datetime
import django_filters

from django_filters import DateRangeFilter, DateFilter, CharFilter
from openpyxl import Workbook
from xhtml2pdf import pisa

from rest_framework import viewsets, filters
from rest_framework.viewsets import ReadOnlyModelViewSet, ModelViewSet, ReadOnlyModelViewSet
from rest_framework.authentication import SessionAuthentication, BasicAuthentication
from rest_framework.permissions import IsAuthenticated
from rest_framework.parsers import MultiPartParser
from drf_renderer_xlsx.mixins import XLSXFileMixin
from drf_renderer_xlsx.renderers import XLSXRenderer
from django_filters.rest_framework import DjangoFilterBackend


from django.http import HttpResponse
from django.template.loader import get_template, render_to_string
from django.contrib.auth.mixins import LoginRequiredMixin
from django.template import Context
from django.shortcuts import render
from django.views.generic import TemplateView, DetailView, View, ListView
from django.utils import timezone
from django.db.models import Q

from cgx.models import Agent, Manager
from .models import Carrier
from cgx.serializers import AgentSerializer, ManagerSerializer
from .serializers import CarrierSerializer
from .render import Render, render_to_pdf
from settings import base

# 3rd party app(s)
# from easy_pdf.views import PDFTemplateView, PDFTemplateResponseMixin
from weasyprint import HTML, default_url_fetcher

from django.contrib.auth import get_user_model
User = get_user_model()


class CsrfExemptSessionAuthentication(SessionAuthentication):

    def enforce_csrf(self, request):
        return  # To not perform the csrf check previously happening


# class PDFView(LoginRequiredMixin, PDFTemplateView):
#     template_name = 'carrier/carrier.html'
#     download_filename = 'carrier_report.pdf'

#     def get_context_data(self, **kwargs):
#         return super(PDFView, self).get_context_data(
#             pagesize='A4',
#             title='Carrier Report!',
#             **kwargs
#         )


class CarrierView(LoginRequiredMixin, TemplateView):
    template_name = 'carrier/carrier.html'


class AddCarrierView(LoginRequiredMixin, TemplateView):
    template_name = 'carrier/add_patient_carrier.html'


class AgentViewSet(viewsets.ModelViewSet):
    queryset = Agent.objects.all()
    serializer_class = AgentSerializer


class ManagerViewSet(viewsets.ModelViewSet):
    queryset = Manager.objects.all()
    serializer_class = ManagerSerializer
    

class CarrierFilter(django_filters.FilterSet):
    date_app_rec__gte = DateFilter(field_name='date_app_rec', lookup_expr='gte')
    date_app_rec__lte = DateFilter(field_name='date_app_rec', lookup_expr='lte')
    date_sample_rec__gte = DateFilter(field_name='date_sample_rec', lookup_expr='gte')
    date_sample_rec__lte = DateFilter(field_name='date_sample_rec', lookup_expr='lte')
    date_of_qca__gte = DateFilter(field_name='date_of_qca', lookup_expr='gte')
    date_of_qca__lte = DateFilter(field_name='date_of_qca', lookup_expr='lte')
    date_created__gte = DateFilter(field_name='date_created', lookup_expr='gte')
    date_created__lte = DateFilter(field_name='date_created', lookup_expr='lte')
    patient_name = CharFilter(field_name='patient_name', lookup_expr='icontains')

    class Meta:
        model = Carrier
        fields = ('date_app_rec__gte', 'date_app_rec__lte', 
                'date_sample_rec__gte', 'date_sample_rec__lte',
                  'date_of_qca__gte', 'date_of_qca__lte',
                  'date_created__gte', 'date_created__lte',
                  'patient_name',)


class CarrierViewSet(XLSXFileMixin, ModelViewSet):
    queryset = Carrier.objects.all()
    serializer_class = CarrierSerializer
    authentication_classes = (CsrfExemptSessionAuthentication, BasicAuthentication)
    permission_classes = (IsAuthenticated,)
    parser_classes = (MultiPartParser,) #  for uploading of attachments
    filename = 'carrier-reports.xlsx'
    filter_class = (CarrierFilter)  # filtering From date and To date
    filterset_fields = ('patient_name', 'promo_code')
    search_fields = ('patient_name', 'promo_code', 'insurance_verified_tsg_verification')
    response = HttpResponse(content_type='application/xlsx')
    response['Content-Disposition'] = 'attachment; filename="Carrier-Report.xlsx"'
    

    #  xhtml2pdf
    def get(self, request, queryset, *args, **kwargs):
        pdf = render_to_pdf('carrier_print.html', queryset)
        return HttpResponse(pdf, content_type='application/pdf')

    def get_queryset(self):
        user = self.request.user
        position = self.request.user.position
        if position == 'Manager':
            queryset = Carrier.objects.filter(manager__name=user)
        elif self.request.user.is_superuser:
            queryset = Carrier.objects.all()
        else:
            queryset = Carrier.objects.filter(agent__name=user)
        return queryset
        
    def perform_create(self, serializer):
        user = self.request.user
        promo_code = self.request.user.agent_promo_code
        serializer.save(created_by=user, user_promo_code=promo_code)

    def generate_pdf(self, request):
        template_path = 'carrier/carrier_print.html'

        response = HttpResponse(content_type='application/pdf')
        response['Content-Disposition'] = 'attachment; filename="Carrier-Report.pdf"'

        html = render_to_string(template_path, {'report': report})
        print(html)

        pisaStatus = pisa.CreatePDF(html, dest=response)

        return response


class PdfCarrier(View):

    def get(self, request, carrier_id):
        user = self.request.user
        carrier = Carrier.objects.filter(id=carrier_id).first()
        params = {
        'today': timezone.now(),
        'carrier': carrier,
        'request': request
        }

        response = HttpResponse(content_type='application/pdf')
        response['Content-Disposition'] = "inline; filename=Carrier-Report.pdf"

        html = render_to_string('carrier/carrier_pdf.html', params)
        css = [
            base.BASE_DIR + '/src/css/bootstrap3/css/bootstrap.min.css'
        ]

        HTML(string=html).write_pdf(response, stylesheets=css)
        return response
        # return Render.render('carrier/carrier_print.html', params)

class ExcelCarrier(View):

    def get(self, request, *args, **kwargs):
        user = self.request.user
        carriers = Carrier.objects.filter(agent__name=user)

        response = self.generate_excel(request, carriers)
        return response

    def generate_excel(self, request, carriers):
        workbook = Workbook()
        filename = 'carrier-reports.xlsx'

        worksheet = workbook.active

        worksheet.append(self.excel_header())

        for carrier in carriers:
            worksheet.append(self.excel_row(carrier))

        response = HttpResponse(content_type='application/vnd.ms-excel')
        response['Content-Disposition'] = 'attachment; filename={file}'\
            .format(file = filename)

        workbook.save(response)

        return response

        # SAMPLE FOR EXCEL CONTENT
        # for y in range(1, 101):
        #     for x in range(1, 101):
        #         worksheet.cell(row=x, column=y, value=x*y)

        # workbook.save('/home/station/workstation/files/workbook1.xlsx')

    def excel_row(self, carrier):
        return (
            carrier.patient_name,
            carrier.patient_phone_number,
            carrier.promo_code,
            str(carrier.agent),
            str(carrier.manager),
            carrier.date_app_rec,
            carrier.date_sample_rec,
            str(carrier.type_of_test),
            carrier.date_of_qca,
            carrier.insurance_verified_tsg_verification,
            carrier.telemed_name,
            carrier.date_submitted_to_telemed,
            carrier.date_telemed_returned,
            carrier.date_bioconfim_rec_app,
            carrier.date_paid,
            carrier.date_lab_recorded_app,
            carrier.lab_type,
            carrier.state,
            str(carrier.status),
            carrier.month,
            carrier.insurance_company,
            carrier.notes,
            carrier.rejection_date,
            str(carrier.patient_id_photo),
            str(carrier.insurance_card_photo_front),
            str(carrier.insurance_card_photo_back),
            str(carrier.additional_insurance_cards),
            str(carrier.consent_recording),
            carrier.date_created,
            carrier.created_by,
            carrier.updated_by,
            carrier.user_promo_code
            )

    def excel_header(self):
        return (
            'Patient Name',
            'Patient Phone Number',
            'Promo Code',
            'Agent',
            'Manager',
            'Date App Record',
            'Date Sample Record',
            'Type of Test',
            'Date of QCA',
            'Insurance Verified TSG Verification',
            'Telemed Name',
            'Date Submitted to Telemed',
            'Date Telemed Returned',
            'Date Bioconfim Record App',
            'Date Paid',
            'Date Lab Recorded App',
            'Lab Type',
            'State',
            'status',
            'Month',
            'Insurance Company',
            'Notes',
            'Rejection Date',
            'Patient ID Photo',
            'Insurance Card Photo Front',
            'Insurance Card Photo Back',
            'Additional Insurance Cards',
            'Consent Recording',
            'Date Created',
            'Created by',
            'Updated by',
            'User Promo Code'
            )

templates/cgx/change_list_graph.html
{% extends "admin/change_list.html" %}
{% load staticfiles %}
{% block extrahead %}
    <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"/>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.0/Chart.min.js"></script>
    <script>
        var randomColorGenerator = function () {
            return '#' + (Math.random().toString(16) + '0000000').slice(2, 8);
        };
        var options = {
            responsive: true,
            maintainAspectRatio: true,
            legend: {
                position: 'left'
            },
            title: {
                display: true
            },
            animation: {
                animateScale: true,
                animateRotate: true
            }
        };
        window.onload = function () {
            var ctx = document.getElementById("status-chart");
            {% regroup cl.queryset|dictsort:"status" by status as status_list %}
            var lineChart = new Chart(ctx, {
                type: 'pie',
                data: {
                    labels: [{% for status in status_list %}'{{ status.grouper }}',{% endfor %}],
                    datasets: [{
                        data: [{% for status in status_list %}'{{ status.list|length }}',{% endfor %}],
                        backgroundColor: [{% for status in status_list %}randomColorGenerator(),{% endfor %}]
                    }]
                },
                options: options
            });
            ctx = document.getElementById("state-chart");
            {% regroup cl.queryset|dictsort:"state" by state as state_list %}
            lineChart = new Chart(ctx, {
                type: 'pie',
                data: {
                    labels: [{% for state in state_list %}'{{ state.grouper }}',{% endfor %}],
                    datasets: [{
                        data: [{% for state in state_list %}'{{ state.list|length }}',{% endfor %}],
                        backgroundColor: [{% for state in state_list %}randomColorGenerator(),{% endfor %}]
                    }]
                }, options: options
            });
            ctx = document.getElementById("type-of-test-chart");
            {% regroup cl.queryset|dictsort:"type_of_test" by get_type_of_test_display as type_of_test_list %}
            lineChart = new Chart(ctx, {
                type: 'pie',
                data: {
                    labels: [{% for type_of_test in type_of_test_list %}'{{ type_of_test.grouper }}',{% endfor %}],
                    datasets: [{
                        data: [{% for type_of_test in type_of_test_list %}'{{ type_of_test.list|length }}',{% endfor %}],
                        backgroundColor: [{% for type_of_test in type_of_test_list %}randomColorGenerator(),{% endfor %}]
                    }]
                }, options: options
            });
        }
    </script>
{% endblock %}
{% block content %}
    <hr>
    <div class="row">
        <div class="col-md-4">
          <label class="col-sm-offset-6">Status information graph</label>
            <canvas id="status-chart" style="width: 100px !important;"></canvas>
        </div>
        <div class="col-md-4">
          <label class="col-sm-offset-6">State information graph</label>
            <canvas id="state-chart" style="width: 100px !important;"></canvas>
        </div>
        <div class="col-sm-4">
          <label class="col-sm-offset-6">Type of Test information graph</label>
            <canvas id="type-of-test-chart" style="width: 100px !important;"></canvas>
        </div>
    </div>
    {{ block.super }}
{% endblock %}

templates/cgx/excel_upload.html
<html>
    <head>
        <title>
            CGX Upload Excel File
        </title>
    </head>
    <body style="margin-top: 30px;margin-left: 30px;">
        <form action="{% url "cgx:cgx_excel" %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <input type="file"
                   title="Upload excel file"
                   name="excel_file"
                   style="border: 1px solid black; padding: 5px;"
                   required="required">
            <p>
            <input type="submit"
                   value="Upload"
                   style="border: 1px solid green; padding:5px; border-radius: 2px; cursor: pointer;">
        </form>

        <p></p>
        <hr>

        {% for row in excel_data %}
            {% for cell in row %}
                {{ cell }}&nbsp;&nbsp;
            {% endfor %}
            <br>
        {% endfor %}
    </body>
</html>

templates/cgx/upload_bcm.html
<html>
    <head>
        <title>
            Upload BCM
        </title>
    </head>
    <body style="margin-top: 30px;margin-left: 30px;">
        <form action="{% url "cgx:upload_bcm" %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <input type="file"
                   title="Upload excel file"
                   name="excel_file"
                   style="border: 1px solid black; padding: 5px;"
                   required="required">
            <p>
            <input type="submit"
                   value="Upload"
                   style="border: 1px solid green; padding:5px; border-radius: 2px; cursor: pointer;">
        </form>

        <p></p>
        <hr>
    </body>
</html>