carrier/urls.py
from django.urls import path
from . import views

app_name='carrier'

urlpatterns = [
    path('view-carrier', views.CarrierView.as_view(), name="view-carrier"),
    path('add-carrier', views.AddCarrierView.as_view(), name="add-carrier"),
    path('<uuid:carrier_id>/carrier-report.pdf', views.PdfCarrier.as_view(), name="print_carrier"),
    path('carrier-report.xlsx', views.ExcelCarrier.as_view(), name="excel_carrier"),
]

cgx/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = 'cgx'

urlpatterns = [
    path('view-bioconfirm', views.BioConfirmView.as_view(), name='bioconfirm'),
    path('add-bioconfirm', views.AddBioConfirmView.as_view(), name='add-bioconfirm'),
    path('cgx_upload_data/', views.upload_bcm, name='upload_bcm'),
    path('<uuid:bioconfirm_id>/bioconfirm-report.pdf', views.PdfBioconfirm.as_view(), name='bioconfirm_print'),
]

paincreamandfootbath/urls.py
from django.urls import path

from . import views

app_name = 'pcfb'
urlpatterns = [
    path('view-rx', views.PcFbView.as_view(), name="view-pcandfb"),
    path('add-rx', views.AddPcFbView.as_view(), name="add-pcandfb"),
    path('<uuid:pcfb_id>/pcfb-report.pdf', views.PdfPCFB.as_view(), name='pcfb_print'),
]

web/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = 'web'
urlpatterns = [
    path('', views.LoginView.as_view(), name='login'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('home/', views.HomeView.as_view(), name='home'),
    path('add', views.AddRecordView.as_view(), name='add_record')

]

templates/add_records_all_apps.html
{% extends 'base/base.html' %}

{% block title %}
Add data | TSG System
{% endblock %}

{% block content %}
<div class="container">
  <div>
    <a class="btn btn-outline-primary" href="{% url 'web:home' %}" style="margin-top: 20px;">&laquo; Back to Overview</a>
  </div>
  <div class="row">
    <div class="col-md-12">
        <div id="accordion">
        <div class="card" id="card-table">
          <div class="card-header" id="headingOne">
            <h5 class="mb-0">
              <button class="btn btn-link collapsed" data-toggle="collapse" data-target="#collapseBio" aria-expanded="true" aria-controls="collapseBio">
                Bio Confirm Master
              </button>
            </h5>
          </div>
          <!-- collapse card -->
          <div id="collapseBio" class="collapse" aria-labelledby="headingOne" data-parent="#accordion">
            <!-- patient info -->
            {% include 'cgx/add_patient_bioconfirm.html' %}
            <!-- end patient info -->
          </div>
          <!-- end collapse card -->
        </div>
        <div class="card" id="card-table">
          <div class="card-header" id="headingTwo">
            <h5 class="mb-0">
              <button class="btn btn-link collapsed" data-toggle="collapse" data-target="#collapseCarrier" aria-expanded="false" aria-controls="collapseCarrier">
                Carrier
              </button>
            </h5>
          </div>
          <div id="carrier-app">
              <div id="collapseCarrier" class="collapse" aria-labelledby="headingTwo" data-parent="#accordion">
                {% include 'carrier/add_patient_carrier.html' %}
              </div>
          </div>
        </div>
        <div class="card" id="card-table">
          <!-- card header -->
          <div class="card-header" id="headingThree">
            <h5 class="mb-0">
              <button class="btn btn-link collapsed" data-toggle="collapse" data-target="#collapseDME" aria-expanded="false" aria-controls="collapseDME">
                DME
              </button>
            </h5>
          </div>
          <!-- end card header -->
          <div id="collapseDME" class="collapse" aria-labelledby="headingThree" data-parent="#accordion">
            {% include 'dme/add_patient_dme.html' %}
          </div>
        </div>
        {% if request.user.is_superuser %}
        <div class="card" id="card-table">
          <div class="card-header" id="headingFour">
            <h5 class="mb-0">
              <button class="btn btn-link collapsed" data-toggle="collapse" data-target="#collapseInsurance" aria-expanded="false" aria-controls="collapseInsurance">
                Insurance
              </button>
            </h5>
          </div>
          <div id="collapseInsurance" class="collapse" aria-labelledby="headingFour" data-parent="#accordion">
            <!-- insurance info -->
            {% include 'insurance/add_info_insurance.html' %}
            <!-- end insurance info -->
          </div>
        </div>
        {% endif %}
        <div class="card" id="card-table">
          <div class="card-header" id="headingFive">
            <h5 class="mb-0">
              <button class="btn btn-link collapsed" data-toggle="collapse" data-target="#collapsePainCreamAndFootBath" aria-expanded="false" aria-controls="collapsePainCreamAndFootBath">
                Rx
              </button>
            </h5>
          </div>
          <div id="collapsePainCreamAndFootBath" class="collapse" aria-labelledby="headingFive" data-parent="#accordion">
            <!-- insurance info -->
            {% include 'paincreamandfootbath/add_patient_pc_and_fb.html' %}
            <!-- end insurance info -->
          </div>
        </div>
        </div>
      </div>
    </div>
</div>
{% endblock %}

templates/add_request_supplies.html
{% extends 'base/base.html' %}

{% block title %}
Request Supplies | TSG System
{% endblock %}

{% block content %}
<div class="container">
    <div>
        <a class="btn btn-outline-primary" href="{% url 'web:home' %}" style="margin-top: 20px;">&laquo; Back to
            Overview</a>
    </div>
    <div class="row">
        <div class="col-md-12">
                <div class="card" id="card-table">
                    <div class="card-header">
                        Request Supplies
                    </div>
                    <div class="card-body">
                        <!-- patient info -->
                        {% include 'supplies/add_supplies.html' %}
                        <!-- end patient info -->
                    </div>
                    <!-- end collapse card -->
                </div>
        </div>
    </div>
</div>
{% endblock %}

templates/home.html
{% extends 'base/base.html' %}

{% load static %}
{% load staticfiles %}

{% block title %}
Home | TSG Systems
{% endblock %}

{% block content %}
<div class="tsg-tabs">
  <div class="nav-tabs-container">
    <div class="container">
      <div class="card-group">
        <div class="col-lg-3 col-md-4 col-sm-6">
          <div class="card mb-3">
            <a href="{% url 'cgx:bioconfirm' %}" class="card-header">Bio Confirm Master</a>
            <div class="card-body">
              <p class="card-text">View all <strong>Bio Confirm Master</strong> data that are assigned
                to you.
              </p>
            </div>
          </div>
        </div>

        <div class="col-lg-3 col-md-4 col-sm-6">
          <div class="card mb-3">
            <a href="{% url 'carrier:view-carrier' %}" class="card-header">Carrier</a>
            <div class="card-body">
              <p class="card-text">View all <strong>Carrier</strong> data that are assigned
                to you.
              </p>
            </div>
          </div>
        </div>
        <div class="col-lg-3 col-md-4 col-sm-6">
          <div class="card mb-3">
            <a href="{% url 'cgx:bioconfirm' %}" class="card-header">DME</a>
            <div class="card-body">
              <p class="card-text">View all <strong>DME</strong> data that are assigned
                to you.
              </p>
            </div>
          </div>
        </div>
        <div class="col-lg-3 col-md-4 col-sm-6">
          <div class="card mb-3">
            <a href="{% url 'pcfb:view-pcandfb' %}" class="card-header">Rx</a>
            <div class="card-body">
              <p class="card-text">View all <strong>Rx</strong> data that are assigned
                to you.
              </p>
            </div>
          </div>
        </div>
      </div>
</div>

{% endblock %}

templates/login.html
{% extends 'base/base.html' %}

{% load static %}


{% block title %}
Login | TSG Systems
{% endblock %}

{% block navbar %}
{% endblock %}

{% block content %}
<div class="container" style="padding: 50px 0;">
    <div class="row">
        <div class="column col-10 offset-1 col-sm-10 offset-sm-1  col-md-8 offset-md-2 col-lg-6 offset-lg-3">
            <div class="row">
                <div class="column col-sm-12 text-center">
                    <img class="img-fluid" alt="TSG Systems" src="{% static 'images/logo/TSG_login.png' %}">
                </div>
            </div>
            <div class="row">
                <div class="column col-sm-12">
                    <div class="card">
                        <form class="card-body" action="{% url 'web:login' %}" role="form" method="post" autocomplete="off">{% csrf_token %}
                            <div class="form-group">
                              {% include 'messages/messages.html' %}
                                <label for="username">Username</label>
                                <input type="text" class="form-control" id="username" name="username" placeholder="Username">
                            </div>
                            <div class="form-group">
                                <label for="password">Password</label>
                                <input type="password" class="form-control" id="password" name="password" placeholder="Password">
                            </div>
                            {% if request.GET.next %}
                              <input type="hidden" name="next" value="{{ request.GET.next }}">
                            {% endif %}
                            <button type="submit" class="btn btn-primary btn-block">Login</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block api_load %}
{% endblock %}